services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    platform: linux/amd64
    hostname: splunk
    environment:
      - TZ=${TZ:-Europe/Brussels}
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_PASSWORD
      - SPLUNKBASE_USERNAME
      - SPLUNKBASE_PASSWORD
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/4353/release/1.7.16/download
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    volumes:
      - ./configs/splunk/so1.yml:/tmp/defaults/default.yml
      - ./configs/mycerts/:/opt/splunk/etc/auth/mycerts/
