splunk:
  hec:
    enable: True
    ssl: True
    token: abcd-1234-efgh-5678
    port: 8088
  conf:
    - key: server
      value:
        directory: /opt/splunk/etc/system/local
        content:
          sslConfig:
            sslRootCAPath: $SPLUNK_HOME/etc/auth/mycerts/isrgrootx1.pem
    - key: web
      value:
        directory: /opt/splunk/etc/system/local
        content:
          settings:
            # Do not use $SPLUNK_HOME in web.conf.
            # You must use an absolute path
            enableSplunkWebSSL: true
            privKeyPath: /opt/splunk/etc/auth/mycerts/privkey.pem
            caCertPath: /opt/splunk/etc/auth/mycerts/fullchain.pem
